# Generated by Django 5.2.17 on 2026-09-19 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('youtube_url', models.URLField(verbose_name='link del vídeo (YouTube)')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='imagen de portada')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='duración (minutos)')),
                ('level', models.CharField(choices=[('todos', 'Todos los niveles'), ('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='todos', max_length=20, verbose_name='nivel')),
                ('is_active', models.BooleanField(default=True, verbose_name='visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'clase grabada',
                'verbose_name_plural': 'clases grabadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Vídeo')], default='pdf', max_length=20)),
                ('url', models.URLField(blank=True, verbose_name='enlace del recurso')),
                ('file', models.FileField(blank=True, upload_to='resources/', verbose_name='archivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(blank=True, help_text='Ej: Vinyasa, Hatha, Yin…', max_length=50, verbose_name='tipo de clase')),
                ('preferred_time', models.CharField(blank=True, max_length=100, verbose_name='horario preferido')),
                ('message', models.TextField(help_text='Contá qué te gustaría practicar o en qué horario.', verbose_name='mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('planned', 'Planificada'), ('declined', 'Descartada')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Respuesta visible para el alumno.', verbose_name='respuesta del profe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de clase',
                'verbose_name_plural': 'solicitudes de clases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('youtube_url', models.URLField(help_text='Pegá el link de YouTube de la transmisión en vivo. Se mostrará embebida en la app.', verbose_name='link del streaming (YouTube)')),
                ('scheduled_start', models.DateTimeField(verbose_name='fecha y hora')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duración (minutos)')),
                ('level', models.CharField(choices=[('todos', 'Todos los niveles'), ('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='todos', max_length=20, verbose_name='nivel')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 = sin límite.', verbose_name='cupo máximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clase en vivo',
                'verbose_name_plural': 'clases en vivo',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.liveclass')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'constraints': [models.UniqueConstraint(fields=('user', 'live_class'), name='unique_attendance_user_class')],
            },
        ),
    ]
