# Generated by Django 5.2.17 on 2026-09-19 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono (Lucide) usado en la app.', max_length=50, verbose_name='icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'logro',
                'verbose_name_plural': 'logros',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'logro desbloqueado',
                'verbose_name_plural': 'logros desbloqueados',
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
    ]
