# Generated by Django 5.2.17 on 2026-09-19 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('category', models.CharField(choices=[('nature', 'Sonidos de la naturaleza'), ('breathing', 'Respiración guiada'), ('body_scan', 'Escaneo corporal'), ('ambient', 'Ambiente relajante'), ('meditation', 'Meditación guiada')], default='ambient', max_length=20)),
                ('url', models.URLField(blank=True, verbose_name='enlace del audio')),
                ('file', models.FileField(blank=True, upload_to='audio/', verbose_name='archivo de audio')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='duración (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'audio',
                'verbose_name_plural': 'audios',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=1, verbose_name='minutos')),
                ('session_type', models.CharField(choices=[('meditation', 'Meditación'), ('pomodoro', 'Pomodoro de enfoque'), ('breathing', 'Respiración')], default='meditation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión de meditación',
                'verbose_name_plural': 'sesiones de meditación',
                'ordering': ['-created_at'],
            },
        ),
    ]
